stages:
  - build
  - test
  - release

#image: debian
image: tmkwl/fuseadf-build-debian

#before_script:

build_cmake:
  stage: build
  when: manual
  before_script:
    - apt-get update &&
      apt-get install -y
        cmake
        check &&
      apt-get clean && rm -rf /var/lib/apt/lists/*
  script:
    - util/cmake_release_configure &&
      util/cmake_release_build

build_autotools:
  stage: build
  when: manual
  before_script:
    - apt-get update &&
      apt-get install -y
        autoconf
        automake
        check &&
      apt-get clean && rm -rf /var/lib/apt/lists/*
  script:
    - ./autogen.sh &&
      ./configure &&
      make
#      make check

build_deb:
  stage: build
  when: manual
  before_script:
    - apt-get update &&
      apt-get install -y
        autoconf
        automake
        devscripts
        lintian
        check &&
      apt-get clean && rm -rf /var/lib/apt/lists/*
  script:
    - pwd &&
      util/deb_build.sh
  after_script:
    - mv $CI_PROJECT_DIR/../*.deb $CI_PROJECT_DIR/../fuseadf*orig* $CI_PROJECT_DIR/
  artifacts:
    paths:
      - $CI_PROJECT_DIR/*.deb
      - $CI_PROJECT_DIR/fuseadf*orig*
    when: always
    expire_in: 1 week


install_deb:
  stage: test
  when: manual
  dependencies:
    - build_deb
  before_script:
    - apt-get update &&
      apt-get clean && rm -rf /var/lib/apt/lists/*
  script:
    - apt install -y $CI_PROJECT_DIR/fuseadf*.deb

# https://docs.gitlab.com/ee/user/packages/generic_packages/index.html
upload:
  stage: release
  when: manual
  dependencies:
    - build_deb
    - install_deb
  before_script:
    - apt-get update &&
      apt-get install -y
        curl &&
      apt-get clean && rm -rf /var/lib/apt/lists/*
  script:
#    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file path/to/file.txt "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/my_package/0.0.1/file.txt"'
    - 'cd ${CI_PROJECT_DIR} ; for FILE in *.deb *.tar.gz ; do curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ${FILE} "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/fuseadf/0.1/${FILE}" ; done'

#download:
#  stage: download
#  script:
#    - 'wget --header="JOB-TOKEN: $CI_JOB_TOKEN" ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/my_package/0.0.1/file.txt'
