

default:
	@echo "No default rule. Use: 'build' or 'push'"

build:
#	docker build -t a-docker-registry.whatever/whatever/path/image-name .
	docker build -t tmkwl/fuseadf-build-debian .

push:
#	docker push a-docker-registry.whatever/whatever/path/image-name
	docker push tmkwl/fuseadf-build-debian
