.TH FUSEADF 1 "Jun 2023"
.SH NAME
fuseadf \- Mount an ADF image and read or write files with FUSE.
.SH SYNOPSIS
.B fuseadf
[\fBoptions\fR] <\fIimage_adf\fR> <\fImount point\fR>
.SH DESCRIPTION
\fBfuseadf\fR is a simple libfuse-based filesystem allowing to mount
an ADF image of an Amiga floppy or a hard disk and to read or write 
its contents (volumes/partitions, directories and files).
.PP
Volumes/partitions can be chosen with -p option (not needed for images with
one volume only, ie. floppy disk images).
.
.SH OPTIONS
.TP
.B \-p
Specify volume/partition (number) to mount (default: 0).
.TP
.B \-v
Show version.
.TP
.B \-h
Show usage info.
.SH FUSE options
.TP
.B -o
List of mount options, eg. 'ro' to enforce read-only mount (see also man pages listed below)
.TP
.B \-f
Execute in foreground.
.TP
.B \-d
Execute in foreground with debug output.
.TP
.B \-s
Single-threaded mode (enforced since v0.3, no need to provide it).
.SH SEE ALSO
.BR fusermount (1), mount.fuse (1), mount (8)
.SH AUTHOR
\fBfuseadf\fR was written by \fBTomasz Wolak\fR <tomas.wolak@gmail.com>.
.PP
