.TH FUSEADF 1 "Nov 2022"
.SH NAME
fuseadf \- Mount an ADF image and read files with FUSE.
.SH SYNOPSIS
.B fuseadf
[\fBoptions\fR] <\fIimage_adf\fR> <\fImount point\fR>
.SH DESCRIPTION
\fBfuseadf\fR is a simple libfuse-based filesystem allowing to mount
an ADF image of an Amiga floppy or a hard disk and to read its contents
(volumes/partitions, directories and files).
.PP
Volumes/partitions can be chosen with -p option (not needed for images with
one volume only, ie. floppy disk images).
.
.SH OPTIONS
.TP
.B \-p
Specify volume/partition (number) to mount (default: 0).
.TP
.B \-v
Show version.
.TP
.B \-h
Show usage info.
.SH FUSE options
.TP
.B \-f
Execute in foreground.
.TP
.B \-d
Execute in foreground with debug output.
.TP
.B \-s
Single-threaded mode.
.SH BUGS
It should be used only in FUSE's single-threaded mode(!). Running in
multithreaded mode, with multiple processes accessing the filesystem in
parallel, may result in corrupted data, so beware (esp. when writing data).

(Single-threaded mode may be enforced in the future - but it is not at
the moment and the default for FUSE is multithreaded mode(!), so always
use -s option).
.SH SEE ALSO
.BR fusermount (1), adflib (1)
.SH AUTHOR
\fBfuseadf\fR was written by \fBTomasz Wolak\fR <tomas.wolak@gmail.com>.
.PP
