#!/bin/sh
#
# Prepare data for tests testing the release version
#

CUR_DIR=`pwd`

#[ ! -e build/release/tests/testdata ] && { ln -vs -t build/release/tests ${CUR_DIR}/tests/testdata ; }

cd build/release/tests
../../../tests/prepare_test_data.sh
cd ${CUR_DIR}
